### ISSUE TITLE
How to request and send the code to API?

### ISSUE THREAD

**Issue by CptExorYWWS** [RonaldPM/keyCre#1]
...

**Comment by RonaldPM** [comment]
To generate a key you can send a GET request to `gen.php` with the following parameters,
`nb`: Number of blocks (Number of Dash separated blocks in key) 
`kbs`: Block size (Number of characters in each block)
`nk`: Total number of keys to be generated

This will display the generated keys according to the given specification


To verify the key, send the key to `validate.php` as `k` in a get request. Value `1` in the page represents a valid key and `0` represents an invalid key. I may rewrite this code in future so that it provides responses instead of outputs on page.

Make sure you setup a MySQL db by importing the `keycore.sql` file from the `DB` folder.
